# Generated by Django 4.2.7 on 2023-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='верифицирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_password',
            field=models.IntegerField(blank=True, null=True, verbose_name='ключ для верификации'),
        ),
    ]
