# Generated by Django 4.2.7 on 2023-11-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='massage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='periodicity',
            new_name='period',
        ),
    ]
